In [3]:
nodes = (["A1","A2","A3","A4","A5", "A6", "A7", "A8"]) #create nodes within directed graph

In [4]:
for each_node in nodes:
    print(each_node)

A1
A2
A3
A4
A5
A6
A7
A8


In [5]:
edges =([("A2","A1"),("A1","A4"),("A1","A5"),("A2","A8"),("A6","A2"),
                   ("A4","A8"),("A3","A7"),("A5","A8"),("A5","A3"),("A4","A3")]) 

#add edges without (S) and (T) // important: in Arya(2004) single symbols are labelled differently (i.e. y12 = y21)
#Up to this point, all nodes and edges have been added to the directed graph excluding (S) and (T) Next, an incidence matrix (A) is derived from the nodes and edges previously defined

In [6]:
print("in the following format: Credit An -> Debit An")
for each_edge in edges:
    print(each_edge)
    

in the following format: Credit An -> Debit An
('A2', 'A1')
('A1', 'A4')
('A1', 'A5')
('A2', 'A8')
('A6', 'A2')
('A4', 'A8')
('A3', 'A7')
('A5', 'A8')
('A5', 'A3')
('A4', 'A3')


derive incidence matrix:

In [7]:
def incidence_matrix(A, nodelist=None, edgelist=None, 
                     oriented=True, weight=None):
    
    try:
        import numpy as np
    except ImportError:
        raise ImportError(
          "incidence_matrix() requires numpy: http://scipy.org/ ")
    if nodelist is None:
        nodelist = nodes
    if edgelist is None:
        edgelist = edges
    A = np.zeros((len(nodelist),len(edgelist)))
    node_index = dict( (node,i) for i,node in enumerate(nodelist) )
    for ei,e in enumerate(edgelist):
        (u,v) = e[:2]
        if u == v: continue  # self loops give zero column
        try:
            ui = node_index[u]
            vi = node_index[v]
        except KeyError:
            raise NetworkXError('node %s or %s in edgelist '
                                'but not in nodelist"%(u,v)')
        if weight is None:
            wt = 1
        else:
            if DG.is_multigraph():
                ekey = e[2]
                wt = DG[u][v][ekey].get(weight,1)
            else:
                wt = DG[u][v].get(weight,1)
        if oriented:
            A[ui,ei] = -wt
            A[vi,ei] = wt
        else:
            A[ui,ei] = wt
            A[vi,ei] = wt
    return np.asmatrix(A)
# (http://networkx.github.io/documentation/networkx-1.7/_modules/networkx/linalg/graphmatrix.html)

In [8]:
print(incidence_matrix("A"))

[[ 1. -1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0. -1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  1.  1.]
 [ 0.  1.  0.  0.  0. -1.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.  0.  0. -1. -1.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  1.  0.  1.  0.  0.]]


In [9]:
import numpy as np
x = np.array([3, 1, -1, 1, -3, -7, 3, 3]).reshape(8, 1)
y = np.array([4, 1, 0, 2, 7, 0, 3, 1, 2, 0]).reshape(10, 1)
c = incidence_matrix("A")*y

#use dot() function for multiplication of matrices?

In [10]:
print(c)

[[ 3.]
 [ 1.]
 [-1.]
 [ 1.]
 [-3.]
 [-7.]
 [ 3.]
 [ 3.]]


In [20]:
if x.all() == c.all():
    print("consistent transaction vector")
else:
    print ("transaction vector inconsistent!")

consistent transaction vector
