In [1]:
clear

In [2]:
import os

In [3]:
os.chdir("/Users/chris/Desktop/Dropbox/MasterThesisAFM/Coding")
os.getcwd()

'/Users/chris/Desktop/Dropbox/MasterThesisAFM/Coding'

In [4]:
import csv

In [5]:
#CREATE DICTIONARY FOR NODES
def reader(filename):
    for (lineno, line) in enumerate(open(filename)):
        if lineno > 0: # skip header
            yield line

filename = "coldwater_nodes.csv"
(l_nodes, nodenames, beg, end, change) = zip(*( row for row in csv.reader(reader(filename))))

d_nodes = dict(zip(l_nodes, change))

#for k, v in d_nodes.items():
    #print(k," ",v)



In [6]:
#{k:int(v) for k, v in dict_nodes.items()} #dictionary comprehension if change needed

In [7]:
import networkx as nx 
DG=nx.DiGraph()

In [8]:
#ADD SOURCE/SINK EDGES, by definition all nodes are included in edgelist
for k, v in d_nodes.items():
    
    if int(v)<0:
        DG.add_edge('S',k)
        nx.set_edge_attributes(DG, 'capacity', {('S',k): abs(int(v))})
        print("from 'S' to", k, "with capacity =",abs(int(v)))

    if int(v)>0:
        DG.add_edge(k,"T")
        nx.set_edge_attributes(DG, 'capacity', {(k, 'T'): abs(int(v))})
        print("from", k,"to 'T'","with capacity =",int(v))

from 'S' to A9 with capacity = 10264
from A7 to 'T' with capacity = 6581
from 'S' to A10 with capacity = 9214
from A23 to 'T' with capacity = 7857
from 'S' to A11 with capacity = 4548
from A5 to 'T' with capacity = 1419
from A21 to 'T' with capacity = 107083
from A3 to 'T' with capacity = 27772
from A20 to 'T' with capacity = 120126
from A12 to 'T' with capacity = 451
from 'S' to A13 with capacity = 843
from A8 to 'T' with capacity = 1620
from A4 to 'T' with capacity = 2273
from A6 to 'T' with capacity = 3673
from 'S' to A22 with capacity = 57
from 'S' to A14 with capacity = 145
from A2 to 'T' with capacity = 1677
from 'S' to A19 with capacity = 246697
from 'S' to A1 with capacity = 8764


In [9]:
#nx.edges(DG) #check edges that for source/sink nodes

In [10]:
#ADD TRANSACTION EDGES
def reader(filename2):
    for (lineno, line) in enumerate(open(filename2)):
        if lineno > 0: # skip header
            yield line

filename2 = "coldwater_edges.csv"
(from_, to_) = zip(*( row for row in csv.reader(reader(filename2))))

l_edges = list(zip(from_, to_))

for f,t in l_edges:
    DG.add_edge(f,t)

In [11]:
nx.edges(DG) #check edges

[('A7', 'T'),
 ('A11', 'A5'),
 ('A5', 'T'),
 ('A12', 'A13'),
 ('A12', 'T'),
 ('A3', 'A10'),
 ('A3', 'T'),
 ('A13', 'A14'),
 ('S', 'A9'),
 ('S', 'A13'),
 ('S', 'A14'),
 ('S', 'A10'),
 ('S', 'A22'),
 ('S', 'A11'),
 ('S', 'A19'),
 ('S', 'A1'),
 ('A23', 'A12'),
 ('A23', 'A13'),
 ('A23', 'A14'),
 ('A23', 'T'),
 ('A20', 'A3'),
 ('A20', 'T'),
 ('A8', 'A22'),
 ('A8', 'T'),
 ('A21', 'A4'),
 ('A21', 'A6'),
 ('A21', 'A10'),
 ('A21', 'T'),
 ('A21', 'A11'),
 ('A21', 'A22'),
 ('A21', 'A7'),
 ('A6', 'A5'),
 ('A6', 'T'),
 ('A22', 'A9'),
 ('A4', 'T'),
 ('A2', 'A19'),
 ('A2', 'A1'),
 ('A2', 'T'),
 ('A1', 'A9'),
 ('A1', 'A12'),
 ('A1', 'A8'),
 ('A1', 'A4'),
 ('A1', 'A7'),
 ('A1', 'A10'),
 ('A1', 'A11')]

In [12]:
print('no. of nodes:',DG.number_of_nodes())
print('no. of edges:',DG.number_of_edges())
print('maximum flow:',nx.maximum_flow_value(DG, s='S', t='T'))
print('minimum cut: ',nx.minimum_cut_value(DG, s="S", t="T"))

no. of nodes: 21
no. of edges: 45
maximum flow: 10183
minimum cut:  10183


In [13]:
#run max-flow min cut algorithm
data = nx.maximum_flow(DG, s="S", t="T")
nx.maximum_flow(DG, s="S", t="T")

(10183,
 {'A1': {'A10': 0,
   'A11': 0,
   'A12': 451,
   'A4': 2273,
   'A7': 4420,
   'A8': 1620,
   'A9': 0},
  'A10': {},
  'A11': {'A5': 1419},
  'A12': {'A13': 0, 'T': 451},
  'A13': {'A14': 0},
  'A14': {},
  'A19': {},
  'A2': {'A1': 0, 'A19': 0, 'T': 0},
  'A20': {'A3': 0, 'T': 0},
  'A21': {'A10': 0, 'A11': 0, 'A22': 0, 'A4': 0, 'A6': 0, 'A7': 0, 'T': 0},
  'A22': {'A9': 0},
  'A23': {'A12': 0, 'A13': 0, 'A14': 0, 'T': 0},
  'A3': {'A10': 0, 'T': 0},
  'A4': {'T': 2273},
  'A5': {'T': 1419},
  'A6': {'A5': 0, 'T': 0},
  'A7': {'T': 4420},
  'A8': {'A22': 0, 'T': 1620},
  'A9': {},
  'S': {'A1': 8764,
   'A10': 0,
   'A11': 1419,
   'A13': 0,
   'A14': 0,
   'A19': 0,
   'A22': 0,
   'A9': 0},
  'T': {}})

In [14]:
y1 = []

In [15]:
for x, z in l_edges:
    try:
        y1.append(data[1][x][z])
    except:
        pass

In [16]:
import numpy as np
print(np.__version__)



1.11.1


In [17]:
y = np.array(y1).reshape(len(l_edges),1)
print(y)

[[   0]
 [   0]
 [   0]
 [2273]
 [4420]
 [ 451]
 [1620]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [   0]
 [1419]
 [   0]
 [   0]
 [   0]]


***DERIVE INCIDENCE MATRIX***

In [18]:
def incidence_matrix(A, nodelist=None, edgelist=None, 
                     oriented=True, weight=None):
    if nodelist is None:
        nodelist = l_nodes
    if edgelist is None:
        edgelist = l_edges
    A = np.zeros((len(nodelist),len(edgelist)))
    node_index = dict( (node,i) for i,node in enumerate(nodelist) )
    for ei,e in enumerate(edgelist):
        (u,v) = e[:2]
        if u == v: continue  # self loops give zero column
        try:
            ui = node_index[u]
            vi = node_index[v]
        except KeyError:
            raise NetworkXError('node %s or %s in edgelist '
                                'but not in nodelist"%(u,v)')
        if weight is None:
            wt = 1
        else:
            if DG.is_multigraph():
                ekey = e[2]
                wt = DG[u][v][ekey].get(weight,1)
            else:
                wt = DG[u][v].get(weight,1)
        if oriented:
            A[ui,ei] = -wt
            A[vi,ei] = wt
        else:
            A[ui,ei] = wt
            A[vi,ei] = wt
    return np.asmatrix(A)

In [19]:
A = incidence_matrix("A")
print(A)

[[ 1. -1. -1. -1. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  

***PERFORM CONSISTENCY CHECK***

In [20]:
#derive vector x
int_change = []
for value in change:
    int_change.append(int(value))
    
x = np.array(int_change).reshape(len(l_nodes), 1)
print(x)

[[  -8764]
 [   1677]
 [  27772]
 [   2273]
 [   1419]
 [   3673]
 [   6581]
 [   1620]
 [ -10264]
 [  -9214]
 [  -4548]
 [    451]
 [   -843]
 [   -145]
 [-246697]
 [ 120126]
 [ 107083]
 [    -57]
 [   7857]]


In [21]:
#check if Ay = x relationship holds
Ay = incidence_matrix("A")*y
print(Ay)

[[-8764.]
 [    0.]
 [    0.]
 [ 2273.]
 [ 1419.]
 [    0.]
 [ 4420.]
 [ 1620.]
 [    0.]
 [    0.]
 [-1419.]
 [  451.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]
 [    0.]]


In [24]:
#test = np.subtract(Ay, x)
#print(test)

In [25]:
if x.all == Ay.all:
    print("consistent y")
else:
    print("inconsistent y")

inconsistent y
