In [89]:
clear

In [90]:
import os

In [91]:
os.chdir("/Users/chris/Desktop/Dropbox/MasterThesisAFM/Coding")
os.getcwd()

'/Users/chris/Desktop/Dropbox/MasterThesisAFM/Coding'

In [92]:
import csv

In [93]:
#CREATE DICTIONARY FOR NODES
def reader(filename):
    for (lineno, line) in enumerate(open(filename)):
        if lineno > 0: # skip header
            yield line

filename = "coldwater_nodes.csv"
(l_nodes, nodenames, beg, end, change) = zip(*( row for row in csv.reader(reader(filename))))

d_nodes = dict(zip(l_nodes, change))

#for k, v in d_nodes.items():
    #print(k," ",v)



In [94]:
#{k:int(v) for k, v in dict_nodes.items()} #dictionary comprehension if change needed

In [95]:
import networkx as nx 
DG=nx.DiGraph()

In [96]:
#ADD SOURCE/SINK EDGES, by definition all nodes are included in edgelist
for k, v in d_nodes.items():
    
    if int(v)<0:
        DG.add_edge('S',k)
        nx.set_edge_attributes(DG, 'capacity', {('S',k): abs(int(v))})
        print("from 'S' to", k, "with capacity =",abs(int(v)))

    if int(v)>0:
        DG.add_edge(k,"T")
        nx.set_edge_attributes(DG, 'capacity', {(k, 'T'): abs(int(v))})
        print("from", k,"to 'T'","with capacity =",int(v))

from 'S' to A1 with capacity = 8764
from 'S' to A13 with capacity = 843
from 'S' to A14 with capacity = 145
from A7 to 'T' with capacity = 6581
from 'S' to A19 with capacity = 246697
from 'S' to A10 with capacity = 9214
from A4 to 'T' with capacity = 2273
from A8 to 'T' with capacity = 1620
from A22 to 'T' with capacity = 57
from A2 to 'T' with capacity = 1677
from 'S' to A11 with capacity = 4548
from 'S' to A9 with capacity = 10264
from A21 to 'T' with capacity = 107083
from A5 to 'T' with capacity = 1419
from A3 to 'T' with capacity = 27772
from A20 to 'T' with capacity = 120126
from A23 to 'T' with capacity = 7857
from A6 to 'T' with capacity = 3673
from A12 to 'T' with capacity = 451


In [97]:
#nx.edges(DG) #check edges that for source/sink nodes

In [98]:
#ADD TRANSACTION EDGES
def reader(filename2):
    for (lineno, line) in enumerate(open(filename2)):
        if lineno > 0: # skip header
            yield line

filename2 = "coldwater_edges.csv"
(from_, to_) = zip(*( row for row in csv.reader(reader(filename2))))

l_edges = list(zip(from_, to_))

for f,t in l_edges:
    DG.add_edge(f,t)
    DG.edge[f][t]['capacity'] = 9999999999
  

In [99]:
nx.edges(DG) #check edges

[('A1', 'A7'),
 ('A1', 'A10'),
 ('A1', 'A4'),
 ('A1', 'A8'),
 ('A1', 'A11'),
 ('A1', 'A12'),
 ('A2', 'T'),
 ('A2', 'A1'),
 ('A7', 'T'),
 ('A7', 'A21'),
 ('A19', 'A2'),
 ('A10', 'A21'),
 ('A10', 'A3'),
 ('A4', 'T'),
 ('A4', 'A21'),
 ('A8', 'T'),
 ('A22', 'T'),
 ('A22', 'A8'),
 ('A22', 'A21'),
 ('A13', 'A23'),
 ('A13', 'A14'),
 ('A11', 'A21'),
 ('A14', 'A23'),
 ('A21', 'T'),
 ('A5', 'T'),
 ('A5', 'A6'),
 ('A5', 'A11'),
 ('A3', 'T'),
 ('A3', 'A20'),
 ('S', 'A1'),
 ('S', 'A9'),
 ('S', 'A19'),
 ('S', 'A10'),
 ('S', 'A13'),
 ('S', 'A11'),
 ('S', 'A14'),
 ('A6', 'T'),
 ('A6', 'A21'),
 ('A20', 'T'),
 ('A9', 'A1'),
 ('A9', 'A22'),
 ('A23', 'T'),
 ('A12', 'T'),
 ('A12', 'A13'),
 ('A12', 'A23')]

In [100]:
print('no. of nodes:',DG.number_of_nodes())
print('no. of edges:',DG.number_of_edges())
print('maximum flow:',nx.maximum_flow_value(DG, s='S', t='T'))
print('minimum cut: ',nx.minimum_cut_value(DG, s="S", t="T"))

no. of nodes: 21
no. of edges: 45
maximum flow: 275497
minimum cut:  275497


In [101]:
#run max-flow min cut algorithm
data = nx.maximum_flow(DG, s="S", t="T")
nx.maximum_flow(DG, s="S", t="T")

(275497,
 {'A1': {'A10': 147898,
   'A11': 0,
   'A12': 8308,
   'A4': 2273,
   'A7': 91315,
   'A8': 0},
  'A10': {'A21': 9214, 'A3': 147898},
  'A11': {'A21': 4548},
  'A12': {'A13': 988, 'A23': 6869, 'T': 451},
  'A13': {'A14': 145, 'A23': 843},
  'A14': {'A23': 145},
  'A19': {'A2': 246697},
  'A2': {'A1': 245020, 'T': 1677},
  'A20': {'T': 120126},
  'A21': {'T': 107083},
  'A22': {'A21': 8587, 'A8': 1620, 'T': 57},
  'A23': {'T': 7857},
  'A3': {'A20': 120126, 'T': 27772},
  'A4': {'A21': 0, 'T': 2273},
  'A5': {'A11': 0, 'A6': 0, 'T': 0},
  'A6': {'A21': 0, 'T': 0},
  'A7': {'A21': 84734, 'T': 6581},
  'A8': {'T': 1620},
  'A9': {'A1': 0, 'A22': 10264},
  'S': {'A1': 4774,
   'A10': 9214,
   'A11': 4548,
   'A13': 0,
   'A14': 0,
   'A19': 246697,
   'A9': 10264},
  'T': {}})

In [102]:
y1 = []

In [103]:
for x, z in l_edges:
    try:
        y1.append(data[1][x][z])
    except:
        pass

In [104]:
import numpy as np
print(np.__version__)



1.11.1


In [105]:
y = np.array(y1).reshape(len(l_edges),1)
print(y)

[[245020]
 [147898]
 [     0]
 [  2273]
 [ 91315]
 [  8308]
 [     0]
 [     0]
 [246697]
 [  9214]
 [120126]
 [     0]
 [  4548]
 [     0]
 [ 84734]
 [  6869]
 [   843]
 [   145]
 [  1620]
 [ 10264]
 [   145]
 [   988]
 [     0]
 [     0]
 [147898]
 [  8587]]


***DERIVE INCIDENCE MATRIX***

In [106]:
def incidence_matrix(A, nodelist=None, edgelist=None, 
                     oriented=True, weight=None):
    if nodelist is None:
        nodelist = l_nodes
    if edgelist is None:
        edgelist = l_edges
    A = np.zeros((len(nodelist),len(edgelist)))
    node_index = dict( (node,i) for i,node in enumerate(nodelist) )
    for ei,e in enumerate(edgelist):
        (u,v) = e[:2]
        if u == v: continue  # self loops give zero column
        try:
            ui = node_index[u]
            vi = node_index[v]
        except KeyError:
            raise NetworkXError('node %s or %s in edgelist '
                                'but not in nodelist"%(u,v)')
        if weight is None:
            wt = 1
        else:
            if DG.is_multigraph():
                ekey = e[2]
                wt = DG[u][v][ekey].get(weight,1)
            else:
                wt = DG[u][v].get(weight,1)
        if oriented:
            A[ui,ei] = -wt
            A[vi,ei] = wt
        else:
            A[ui,ei] = wt
            A[vi,ei] = wt
    return np.asmatrix(A)

In [107]:
A = incidence_matrix("A")
print(A)

[[ 1. -1. -1. -1. -1. -1. -1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  

***PERFORM CONSISTENCY CHECK***

In [108]:
#derive vector x
int_change = []
for value in change:
    int_change.append(int(value))
    
x = np.array(int_change).reshape(len(l_nodes), 1)
print(x)

[[  -8764]
 [   1677]
 [  27772]
 [   2273]
 [   1419]
 [   3673]
 [   6581]
 [   1620]
 [ -10264]
 [  -9214]
 [  -4548]
 [    451]
 [   -843]
 [   -145]
 [-246697]
 [ 120126]
 [ 107083]
 [     57]
 [   7857]]


In [109]:
#check if Ay = x relationship holds
Ay = incidence_matrix("A")*y
np.set_printoptions(suppress=True)
print(Ay)

[[  -4774.]
 [   1677.]
 [  27772.]
 [   2273.]
 [      0.]
 [      0.]
 [   6581.]
 [   1620.]
 [ -10264.]
 [  -9214.]
 [  -4548.]
 [    451.]
 [      0.]
 [      0.]
 [-246697.]
 [ 120126.]
 [ 107083.]
 [     57.]
 [   7857.]]


In [22]:
#test = np.subtract(Ay, x)
#print(test)

In [23]:
if x.all == Ay.all:
    print("consistent y")
else:
    print("inconsistent y")

inconsistent y


99999999