In [38]:
clear

In [39]:
import os

In [40]:
os.chdir("/Users/chris/Desktop/Dropbox/MasterThesisAFM/Coding")
os.getcwd()

'/Users/chris/Desktop/Dropbox/MasterThesisAFM/Coding'

In [41]:
import csv

In [42]:
#CREATE DICTIONARY FOR NODES
def reader(filename):
    for (lineno, line) in enumerate(open(filename)):
        if lineno > 0: # skip header
            yield line

filename = "input_nodes_sma.csv"
(l_nodes, nodenames, beg, end, change) = zip(*( row for row in csv.reader(reader(filename))))

d_nodes = dict(zip(l_nodes, change))

In [43]:
import networkx as nx 
DG=nx.DiGraph()

In [44]:
#ADD SOURCE/SINK EDGES, by definition all nodes are included in edgelist
for k, v in d_nodes.items():
    
    if int(v)<0:
        DG.add_edge('S',k)
        nx.set_edge_attributes(DG, 'capacity', {('S',k): abs(int(v))})
        print("from 'S' to", k, "with capacity =",abs(int(v)))

    if int(v)>0:
        DG.add_edge(k,"T")
        nx.set_edge_attributes(DG, 'capacity', {(k, 'T'): abs(int(v))})
        print("from", k,"to 'T'","with capacity =",int(v))

from 'S' to A1 with capacity = 3090
from A2 to 'T' with capacity = 5140
from A3 to 'T' with capacity = 33872
from A4 to 'T' with capacity = 10328
from A5 to 'T' with capacity = 15117
from A6 to 'T' with capacity = 48415
from A7 to 'T' with capacity = 7205
from A8 to 'T' with capacity = 273
from A9 to 'T' with capacity = 430
from A10 to 'T' with capacity = 5545
from A11 to 'T' with capacity = 59007
from 'S' to A12 with capacity = 2505
from 'S' to A13 with capacity = 88689
from 'S' to A14 with capacity = 4864
from 'S' to A15 with capacity = 37192
from 'S' to A16 with capacity = 744984
from A17 to 'T' with capacity = 2860
from A19 to 'T' with capacity = 412120
from A20 to 'T' with capacity = 124606
from A21 to 'T' with capacity = 37450
from A22 to 'T' with capacity = 105588
from 'S' to A23 with capacity = 4486
from A24 to 'T' with capacity = 17854


In [45]:
#nx.edges(DG) #check edges that for source/sink nodes

In [46]:
#ADD TRANSACTION EDGES
def reader(filename2):
    for (lineno, line) in enumerate(open(filename2)):
        if lineno > 0: # skip header
            yield line

filename2 = "input_edges_sma.csv"
(from_, to_) = zip(*( row for row in csv.reader(reader(filename2))))

l_edges = list(zip(from_, to_))

for f,t in l_edges:
    DG.add_edge(f,t)
    DG.edge[f][t]['capacity'] = 9999999999
  

In [47]:
print('no. of nodes:',DG.number_of_nodes())
print('no. of edges:',DG.number_of_edges())
print('maximum flow:',nx.maximum_flow_value(DG, s='S', t='T'))
print('minimum cut: ',nx.minimum_cut_value(DG, s="S", t="T"))

no. of nodes: 25
no. of edges: 57
maximum flow: 885810
minimum cut:  885810


In [48]:
#run max-flow min cut algorithm
data = nx.maximum_flow(DG, s="S", t="T")
nx.maximum_flow(DG, s="S", t="T")

(885810,
 {'A1': {'A21': 3090},
  'A10': {'A7': 739439, 'T': 5545},
  'A11': {'A1': 0, 'A2': 39500, 'A3': 151605, 'A4': 0, 'T': 59007},
  'A12': {'A4': 2505},
  'A13': {'A22': 88689, 'A24': 17854},
  'A14': {'A22': 4864},
  'A15': {'A14': 0, 'A20': 124606},
  'A16': {'A10': 744984, 'A5': 0},
  'A17': {'T': 2860},
  'A19': {'T': 412120},
  'A2': {'A21': 34360, 'T': 5140},
  'A20': {'T': 124606},
  'A21': {'T': 37450},
  'A22': {'T': 105588},
  'A23': {'A7': 4486},
  'A24': {'T': 17854},
  'A3': {'A21': 0, 'A7': 117733, 'T': 33872},
  'A4': {'A17': 2860, 'A19': 412120, 'A5': 15117, 'T': 10328},
  'A5': {'A7': 0, 'T': 15117},
  'A6': {'A7': 0, 'T': 48415},
  'A7': {'A11': 0,
   'A12': 0,
   'A13': 17854,
   'A15': 87414,
   'A4': 437920,
   'A6': 48415,
   'A8': 250385,
   'A9': 12465,
   'T': 7205},
  'A8': {'A11': 250112, 'T': 273},
  'A9': {'A22': 12035, 'A7': 0, 'T': 430},
  'S': {'A1': 3090,
   'A12': 2505,
   'A13': 88689,
   'A14': 4864,
   'A15': 37192,
   'A16': 744984,
   'A23':

In [49]:
y1 = []

In [50]:
for x, z in l_edges:
    try:
        y1.append(data[1][x][z])
    except:
        pass

In [51]:
import numpy as np
print(np.__version__)



1.11.3


In [52]:
y = np.array(y1).reshape(len(l_edges),1)
print(y)

[[     0]
 [  3090]
 [ 39500]
 [ 34360]
 [151605]
 [  4486]
 [117733]
 [     0]
 [     0]
 [437920]
 [  2860]
 [ 15117]
 [ 48415]
 [     0]
 [250385]
 [250112]
 [     0]
 [ 12465]
 [ 12035]
 [739439]
 [744984]
 [     0]
 [  2505]
 [     0]
 [ 88689]
 [ 17854]
 [  4864]
 [     0]
 [     0]
 [412120]
 [124606]
 [ 87414]
 [ 17854]
 [     0]]


***DERIVE INCIDENCE MATRIX***

In [53]:
def incidence_matrix(A, nodelist=None, edgelist=None, 
                     oriented=True, weight=None):
    if nodelist is None:
        nodelist = l_nodes
    if edgelist is None:
        edgelist = l_edges
    A = np.zeros((len(nodelist),len(edgelist)))
    node_index = dict( (node,i) for i,node in enumerate(nodelist) )
    for ei,e in enumerate(edgelist):
        (u,v) = e[:2]
        if u == v: continue  # self loops give zero column
        try:
            ui = node_index[u]
            vi = node_index[v]
        except KeyError:
            raise NetworkXError('node %s or %s in edgelist '
                                'but not in nodelist"%(u,v)')
        if weight is None:
            wt = 1
        else:
            if DG.is_multigraph():
                ekey = e[2]
                wt = DG[u][v][ekey].get(weight,1)
            else:
                wt = DG[u][v].get(weight,1)
        if oriented:
            A[ui,ei] = -wt
            A[vi,ei] = wt
        else:
            A[ui,ei] = wt
            A[vi,ei] = wt
    return np.asmatrix(A)

In [54]:
A = incidence_matrix("A")
print(A)

[[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  1. -1. -1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.  0.  0. -1.  0.  0. -1.  1. -1.  0.  1. -1.
   0.  1.  0. -1.  0. -1.  0. -1.  0.  0.  0.  0.  0. -1.  0.  1.]
 [ 0.  0.  0.

***PERFORM CONSISTENCY CHECK***

In [55]:
#derive vector x
int_change = []
for value in change:
    int_change.append(int(value))
    
x = np.array(int_change).reshape(len(l_nodes), 1)
print(x)

[[  -3090]
 [   5140]
 [  33872]
 [  10328]
 [  15117]
 [  48415]
 [   7205]
 [    273]
 [    430]
 [   5545]
 [  59007]
 [  -2505]
 [ -88689]
 [  -4864]
 [ -37192]
 [-744984]
 [   2860]
 [ 412120]
 [ 124606]
 [  37450]
 [ 105588]
 [  -4486]
 [  17854]]


In [56]:
#check if Ay = x relationship holds
Ay = incidence_matrix("A")*y
Ay.astype(int)
print(Ay)

[[ -3.09000000e+03]
 [  5.14000000e+03]
 [  3.38720000e+04]
 [  1.03280000e+04]
 [  1.51170000e+04]
 [  4.84150000e+04]
 [  7.20500000e+03]
 [  2.73000000e+02]
 [  4.30000000e+02]
 [  5.54500000e+03]
 [  5.90070000e+04]
 [ -2.50500000e+03]
 [ -8.86890000e+04]
 [ -4.86400000e+03]
 [ -3.71920000e+04]
 [ -7.44984000e+05]
 [  2.86000000e+03]
 [  4.12120000e+05]
 [  1.24606000e+05]
 [  3.74500000e+04]
 [  1.05588000e+05]
 [ -4.48600000e+03]
 [  1.78540000e+04]]


In [57]:
test = np.subtract(Ay, x)
print(test)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
